Update Dockerfile_wordpress

diff --git a/dockerfiles/Dockerfile_wordpress b/dockerfiles/Dockerfile_wordpress
--- a/dockerfiles/Dockerfile_wordpress
+++ b/dockerfiles/Dockerfile_wordpress
@@ -1,47 +1,121 @@
-#Wordpress Apache Sever HCL------------------------------------------
+FROM php:7.2-apache
 
-	FROM ubuntu:18.04
-
-#Wordpres, php und Apache installieren-------------------------------
-
-	RUN apt-get update -y
-	RUN sudo timedatectl set-timezone Europe/Rome
-	RUN apt-get install wordpress php libapache2-mod-php -y 
+# Start Installation
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
 	
+# Ghostscript wird benötigt um PDF previews zu laden
+		ghostscript \
+	; \
+	rm -rf /var/lib/apt/lists/*
 
-#Wordpress Seite in Apache2 erstellen--------------------------------
+# Installiert die php erweiterungen 
+RUN set -ex; \
+	\
+	savedAptMark="$(apt-mark showmanual)"; \
+	\
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
+		libfreetype6-dev \
+		libjpeg-dev \
+		libmagickwand-dev \
+		libpng-dev \
+	; \
+	\
+	docker-php-ext-configure gd --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr; \
+	docker-php-ext-install -j "$(nproc)" \
+		bcmath \
+		exif \
+		gd \
+		mysqli \
+		zip \
+	; \
+	pecl install imagick-3.4.4; \
+	docker-php-ext-enable imagick; \
+	\
+# Resettet apt-mark's "manual" Liste sodass "purge --auto-remove" alle build dependencies entfernen wird
+	apt-mark auto '.*' > /dev/null; \
+	apt-mark manual $savedAptMark; \
+	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
+		| awk '/=>/ { print $3 }' \
+		| sort -u \
+		| xargs -r dpkg-query -S \
+		| cut -d: -f1 \
+		| sort -u \
+		| xargs -rt apt-mark manual; \
+	\
+	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	rm -rf /var/lib/apt/lists/*
 
-	CMD echo "Alias /blog /usr/share/wordpress" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "<Directory /usr/share/wordpress" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Options FollowSymLinks" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "AllowOverride Limit Options FileInfo" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "DirectoryIndex index.php" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Order allow,deny" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Allow from all" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "</Directory>" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "<Directory /usr/share/wordpress/wp-content>" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Options FollowSymLinks" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Order allow,deny" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "Allow from all" > /etc/apache2/sites-available/wordpress.conf 
-	CMD echo "</Directory>" > /etc/apache2/sites-available/wordpress.conf 
-  
-#Wordpress Seite enablen
-	RUN a2ensite wordpress
-	RUN a2enmod rewrite
-	RUN service apache2 reload
+# setzt die recommended PHP.ini settings
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# konfiguriert error Logging
+RUN { \
 
-#Wordpress mit Datenbank verbinden
-	CMD echo "<?php"
-	CMD echo "define('DB_NAME', 'wordpress');" > /etc/wordpress/config-localhost.php
-	CMD echo "define('DB_USER', 'wordpress');" > /etc/wordpress/config-localhost.php
-	CMD echo "define('DB_PASSWORD', 'Test123');" > /etc/wordpress/config-localhost.php
-	CMD echo "define('DB_HOST', '192.168.1.11');" > /etc/wordpress/config-localhost.php
-	CMD echo "define('DB_COLLATE', 'utf8_general_ci');" > /etc/wordpress/config-localhost.php
-	CMD echo "define('WP_CONTENT_DIR', '/usr/share/wordpress/wp-content');" > /etc/wordpress/config-localhost.php
-	CMD echo "?>" > /etc/wordpress/config-localhost.php
+		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+		echo 'display_errors = Off'; \
+		echo 'display_startup_errors = Off'; \
+		echo 'log_errors = On'; \
+		echo 'error_log = /dev/stderr'; \
+		echo 'log_errors_max_len = 1024'; \
+		echo 'ignore_repeated_errors = On'; \
+		echo 'ignore_repeated_source = Off'; \
+		echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
+
+RUN set -eux; \
+	a2enmod rewrite expires; \
+	\
+# RemoteIP konfigurieren
+	a2enmod remoteip; \
+	{ \
+		echo 'RemoteIPHeader X-Forwarded-For'; \
+# Trustet den IP im netzwerk (innerhalb Docker)
+		echo 'RemoteIPTrustedProxy 192.168.1.0/24'; \
+		echo 'RemoteIPTrustedProxy 169.254.0.0/16'; \
+		echo 'RemoteIPTrustedProxy 127.0.0.0/8'; \
+	} > /etc/apache2/conf-available/remoteip.conf; \
+	a2enconf remoteip; \
+
+# (ersetzt alle instances von "%h" mit "%a" in LogFormat)
+	find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +
 
 
-EXPOSE 80
+ENV WORDPRESS_VERSION 5.5.1
+ENV WORDPRESS_SHA1 d3316a4ffff2a12cf92fde8bfdd1ff8691e41931
+
+RUN set -ex; \
+	curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
+	echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
+# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+	tar -xzf wordpress.tar.gz -C /usr/src/; \
+	rm wordpress.tar.gz; \
+	chown -R www-data:www-data /usr/src/wordpress; \ 
+	
+	
+# pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+	mkdir wp-content; \
+	for dir in /usr/src/wordpress/wp-content/*/; do \
+		dir="$(basename "${dir%/}")"; \
+		mkdir "wp-content/$dir"; \
+	done; \
+	chown -R www-data:www-data wp-content; \
+	chmod -R 777 wp-content
 
 VOLUME /var/www/html
-VOLume /data/archive
+VOLUME /data/archive
+EXPOSE 80
+
+COPY docker-entrypoint.sh /usr/local/bin/
+
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["apache2-foreground"]
